import { transform } from "typescript";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
    colors: {
      green: "var(--green)",
      darkergreen: "var(--darkergreen)",
      greenyellow: "var(--greenyellow)",
      lightbackground: "var(--lightbackground)",
      blackbackground: "var(--blackbackground)",
      darkinput: "var(--darkinput)",
      lightblack: "var(--lightblack)",
      footerblack: "var(--footerblack)",
      border: "var(--border)",
      whitetext: "var(--whitetext)",
      darkgreen: "var(--darkgreen)",
      lightgreen: "var(--lightgreen)",
      statbg: "var(--statbg)",
      stattext: "var(--stattext)",
      stattextgray: "var(--stattextgray)",
      contactbg: "var(--contactbg)",
      contactborder: "var(--contactborder)",
      iconborder: "var(--iconborder)",
      graytext: "var(--graytext)",
      floatbg: "var(--floatbg)",
      herotext: "var(--herotext)",
      herotextgray: "var(--herotextgray)",
      whitetext: "var(--whitetext)",
      servicetitlebg1: "var(--servicetitlebg1)",
      servicetitlebg2: "var(--servicetitlebg2)",
      semititletext: "var(--semititletext)",
      gradientlight: "var(--gradientlight)",
      gradientdark: "var(--gradientdark)",
      semititlegray: "var(--semititlegray)",
      desc: "var(--desc)",
      lightbg: "var(--lightbg)",
      aboutdesc: "var(--aboutdesc)",
      featurebg: "var(--featurebg)",
    },
  },
  plugins: [],
};
